Repository clapsheep/walk-or-run-client, pull requests merged in 2024-11, with the labels that each got.

#11 [setting] 함수형 프로그래밍 구조 설계
  src/core/auth/AuthApi.ts
  src/core/auth/AuthHook.ts
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/ChallengeHook.ts
  src/core/challenge/ChallengeType.ts
  src/core/common/ApiResponse.ts
  src/core/goal/GoalApi.ts
  src/core/goal/GoalHook.ts
  src/core/goal/GoalType.ts
  src/core/user/UserApi.ts
  src/core/user/UserHook.ts
  src/core/user/UserType.ts
  src/views/SignupView.vue
Labels: setting

#14 [refactor] 로그인 기능 추가
  .env
  .gitignore
  package-lock.json
  src/core/auth/AuthApi.ts
  src/core/auth/AuthHook.ts
  src/core/auth/AuthType.ts
  src/router/index.ts
  src/stores/userStore.ts
  src/views/ChangePasswordView.vue
  src/views/DashboardView.vue
  src/views/FindPasswordView.vue
  src/views/SigninView.vue
Labels: refactor

#18 [feat] auth 관련기능 전체 리팩토링
  .gitignore
  package-lock.json
  package.json
  src/App.vue
  src/components/atoms/BasicInput.vue
  src/components/atoms/LogoutButton.vue
  src/components/charts/ExerciseTimeChart.vue
  src/components/charts/SpeedChart.vue
  src/components/charts/StepChart.vue
  src/components/molecules/BasicModal.vue
  src/components/organisms/NavigationBar.vue
  src/core/auth/AuthApi.ts
  src/core/auth/AuthHook.ts
  src/core/auth/AuthType.ts
  src/core/auth/composables/useChangePassword.ts
  src/core/auth/composables/useEmailCheck.ts
  src/core/auth/composables/useFindEmail.ts
  src/core/auth/composables/useFindPassword.ts
  src/core/auth/composables/useLogin.ts
  src/core/auth/composables/useLogout.ts
  src/core/auth/composables/useRegisterForm.ts
  src/core/auth/services/findPassword.ts
  src/core/auth/services/loginService.ts
  src/core/auth/services/logoutService.ts
  src/core/auth/utils/validationUtils.ts
  src/core/common/types/ApiResponse.ts
  src/core/record/Record.ts
  src/core/user/UserType.ts
  src/main.ts
  src/router/index.ts
  src/stores/authStore.ts
  src/stores/modalStore.ts
  src/stores/userStore.ts
  src/utils/inputVaildation.ts
  src/utils/inputValidation.ts
  src/views/ChangePasswordView.vue
  src/views/DashboardView.vue
  src/views/FindEmailView.vue
  src/views/FindPasswordView.vue
  src/views/HomeView.vue
  src/views/SigninView.vue
  src/views/SignupView.vue
Labels: refactor

#19 [feat] Challenge 기능 추가
  .env
  package-lock.json
  src/core/auth/AuthApi.ts
  src/core/auth/AuthHook.ts
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/ChallengeHook.ts
  src/core/challenge/ChallengeType.ts
  src/core/challenge/composables/useGetAllChallenges.ts
  src/core/challenge/composables/useGetChallenge.ts
  src/core/challenge/composables/useParticipateChallenge.ts
  src/core/challenge/utils/settingUtils.ts
  src/core/common/PageType.ts
  src/router/index.ts
  src/views/AccountView.vue
  src/views/AdminView.vue
  src/views/ChallengeDetailView.vue
  src/views/ChallengeView.vue
Labels: feat

#20 [feat] Challenge 기능 완성
  .env
  .gitignore
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/ChallengeHook.ts
  src/core/challenge/ChallengeType.ts
  src/core/challenge/composables/useGetChallenge.ts
  src/core/challenge/composables/useParticipateChallenge.ts
  src/views/ChallengeDetailView.vue
Labels: feat

#23 [feat] 마이페이지 기능 구현
  src/components/molecules/GoalSettingModal.vue
  src/core/auth/AuthApi.ts
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/composables/useGetAllChallenges.ts
  src/core/challenge/composables/useGetChallenge.ts
  src/core/challenge/composables/useGetUserChallenges.ts
  src/core/challenge/services/challengesService.ts
  src/core/goal/GoalApi.ts
  src/core/goal/GoalHook.ts
  src/core/goal/composables/useGetUserGoals.ts
  src/core/goal/composables/useGoalSetting.ts
  src/core/user/UserApi.ts
  src/core/user/UserHook.ts
  src/core/user/UserType.ts
  src/core/user/composables/useChangeProfile.ts
  src/core/user/composables/useChangeUserPassword.ts
  src/core/user/composables/useGetUserGoals.ts
  src/core/user/composables/useGetUserInfo.ts
  src/core/user/composables/useMyPage.ts
  src/core/user/services/userInfoService.ts
  src/layouts/MyPageLayout.vue
  src/router/index.ts
  src/views/ChallengeDetailView.vue
  src/views/ChallengeView.vue
  src/views/account/MyChallengesView.vue
  src/views/account/MyPasswordChangeView.vue
  src/views/account/MyPasswordView.vue
  src/views/account/MyUserGoalView.vue
  src/views/account/ProfileView.vue
Labels: feat

#24 [feat] dashboard 구현
  package-lock.json
  package.json
  public/images/csv.svg
  src/assets/images/csv.svg
  src/components/atoms/ChartInfo.vue
  src/components/atoms/FloatingButton.vue
  src/components/charts/BaseChart.vue
  src/components/charts/CadenceChart.vue
  src/components/charts/ChartWrapper.vue
  src/components/charts/DistanceChart.vue
  src/components/charts/ExerciseStats.vue
  src/components/charts/ExerciseTimeChart.vue
  src/components/charts/HeartRateSpeedChart.vue
  src/components/charts/HeartRateZoneChart.vue
  src/components/charts/PaceZoneChart.vue
  src/components/charts/SpeedChart.vue
  src/components/charts/StepChart.vue
  src/components/charts/TimeDistributionChart.vue
  src/components/charts/WeatherChart.vue
  src/components/molecules/ChartHeader.vue
  src/components/molecules/TimeDistributionChart.vue
  src/components/molecules/UploadModal.vue
  src/components/organisms/ChartGrid.vue
  src/components/organisms/GoalsSidebar.vue
  src/core/date/composables/useDateRange.ts
  src/core/date/services/dateService.ts
  src/core/record/composables/useChart.ts
  src/core/record/composables/useUpload.ts
  src/core/record/recordApi.ts
  src/core/record/services/ChartService.ts
  src/core/record/services/uploadService.ts
  src/core/weather/types/WeatherType.ts
  src/core/weather/weatherApi.ts
  src/layouts/DashBoardLayout.vue
  src/router/index.ts
  src/views/DashboardView.vue
Labels: feat

#31 [refactor] 함수형 프로그래밍에 맞게 수정중
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/composables/useCreateChallenge.ts
  src/core/challenge/composables/useDeleteChallenge.ts
  src/core/challenge/composables/useGetActiveChallenges.ts
  src/core/challenge/composables/useGetAllChallenges.ts
  src/core/challenge/composables/useGetEndedChallenges.ts
  src/core/challenge/services/challengesService.ts
  src/views/ChallengeDetailView.vue
  src/views/ChallengeView.vue
  src/views/admin/CreateChallengeView.vue
  src/views/admin/EndedChallengeView.vue
  src/views/admin/OngoingChallengeView.vue
Labels: refactor

#32 [refactor] 공공api ssl미인증으로 인한 날씨 api 변경, 챌린지 디자인 수정
  index.html
  src/components/atoms/DdayBadge.vue
  src/components/atoms/PageSizeSelect.vue
  src/components/atoms/Pagination.vue
  src/components/charts/WeatherChart.vue
  src/components/molecules/ChallengeCard.vue
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/ChallengeType.ts
  src/core/user/UserType.ts
  src/core/weather/composable/useGetWeather.ts
  src/core/weather/services/weatherService.ts
  src/core/weather/types/WeatherType.ts
  src/core/weather/weatherApi.ts
  src/views/ChallengeDetailView.vue
  src/views/ChallengeView.vue
Labels: refactor, feat

#33 [feat] 화면 디자인 수정
  src/components/molecules/FollowButton.vue
  src/components/organisms/NavigationBar.vue
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/ChallengeType.ts
  src/core/user/UserApi.ts
  src/core/user/composables/useChangeProfile.ts
  src/views/FindUserView.vue
  src/views/account/MyChallengesView.vue
  src/views/account/MyFollowView.vue
  src/views/account/MyUserGoalView.vue
  src/views/account/ProfileView.vue
Labels: feat

#40 [feat] 리팩토링 및 최종 배포
  README.md
  src/components/charts/CadenceChart.vue
  src/components/charts/HeartRateSpeedChart.vue
  src/components/charts/HeartRateZoneChart.vue
  src/components/charts/PaceZoneChart.vue
  src/components/molecules/GoalCreateModal.vue
  src/core/auth/AuthApi.ts
  src/core/auth/composables/useChangePassword.ts
  src/core/auth/composables/useFindEmail.ts
  src/core/challenge/AdminChallengeApi.ts
  src/core/challenge/ChallengeApi.ts
  src/core/challenge/ChallengeType.ts
  src/core/challenge/ScheduleType.ts
  src/core/challenge/composables/useCreateChallenge.ts
  src/core/challenge/composables/useDeleteChallengeSchedule.ts
  src/core/challenge/composables/useEditChallenge.ts
  src/core/challenge/composables/useEditSchedules.ts
  src/core/challenge/composables/useGetAllChallenges.ts
  src/core/challenge/composables/useGetEndedChallenges.ts
  src/core/challenge/composables/useGetSchedules.ts
  src/core/challenge/composables/useGetUserChallenges.ts
  src/core/challenge/composables/useParticipateChallenge.ts
  src/core/challenge/composables/useScheduleManage.ts
  src/core/challenge/composables/useUpdateChallengeSchedule.ts
  src/core/challenge/services/challengesService.ts
  src/core/challenge/utils/challengeValidation.ts
  src/core/record/recordApi.ts
  src/core/user/UserApi.ts
  src/router/index.ts
  src/views/NotFoundView.vue
  src/views/account/MyPasswordView.vue
  src/views/admin/CreateChallengeView.vue
  src/views/admin/EditScheduleView.vue
  src/views/admin/ScheduleManageView.vue
Labels: feat

#41 [fix] 오류 수정
  index.html
  public/images/og_img.png
  src/core/challenge/composables/useCreateChallenge.ts
  src/core/goal/composables/useCreateUserGoals.ts
  src/views/admin/CreateChallengeView.vue
Labels: wontfix

#42 [fix] 오류 수정
  index.html
  public/images/og_img.png
  src/core/challenge/composables/useCreateChallenge.ts
  src/core/goal/composables/useCreateUserGoals.ts
  src/views/admin/CreateChallengeView.vue
Labels: wontfix
